CREATE TABLE "all_terrain_route_planner_route" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "all_terrain_route_planner_route_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"routeData" json NOT NULL,
	"distance" real NOT NULL,
	"elevationGain" real NOT NULL,
	"routePreference" varchar(50) DEFAULT 'road' NOT NULL,
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "all_terrain_route_planner_route" ADD CONSTRAINT "all_terrain_route_planner_route_createdById_all_terrain_route_planner_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."all_terrain_route_planner_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "route_created_by_idx" ON "all_terrain_route_planner_route" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "route_title_idx" ON "all_terrain_route_planner_route" USING btree ("title");--> statement-breakpoint
CREATE INDEX "route_created_at_idx" ON "all_terrain_route_planner_route" USING btree ("createdAt");